name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: test
        run: OUTPUT=$(docker-compose up --exit-code-from backend_test | tail -1) && echo $OUTPUT
        shell: bash
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push old version to old image
        run: |
          docker pull omarnashat01/backend_twitterclone:latest
          docker tag omarnashat01/backend_twitterclone:latest omarnashat01/backend_twitterclone:old
          docker push omarnashat01/backend_twitterclone:old
      
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend_twitterclone:latest
      -
        name: Restart Kubernetes deployment
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - 
        run: kubectl rollout restart deployment/twitterclone-team3-deployment
